#! /bin/sh 
#
# This is an init script for openembedded
# Copy it to /etc/init.d/thttpd and type
# > update-rc.d thttpd defaults 60
#


thttpd=/usr/sbin/thttpd
test -x "$thttpd" || exit 0

case "$1" in
  start)
    echo -n "Starting thttpd"
    #ifconfig eth0:0 192.168.1.11 || true
    start-stop-daemon --start --exec $thttpd -- -d @@SRVDIR -p 30000
    echo "."
    ;;
  stop)
    echo -n "Stopping thttpd"
    start-stop-daemon --stop --exec $thttpd
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --signal 1 --exec $thttpd 
    ;;
  restart)
    echo -n "Stopping thttpd"
    start-stop-daemon --stop --exec $thttpd -- -d @@SRVDIR -p 30000
    echo "."
    echo -n "Waiting for thttpd to die off"
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo ""
    echo -n "Starting thttpd"
    start-stop-daemon --start --exec $thttpd -- -d @@SRVDIR -p 30000
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/thttpd {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
